force-app/main/default/objects/IntegrationConfiguration__mdt/IntegrationConfiguration__mdt.object-meta.xml
<CustomObject>
    <description>The base configuration for integrations.</description>
    <label>Integration Configuration</label>
    <pluralLabel>Integration Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationConfiguration__mdt/fields/BaseEndpoint__c.field-meta.xml
<CustomField>
    <fullName>BaseEndpoint__c</fullName>
    <description>The base endpoint for the integration.</description>
    <inlineHelpText>The base endpoint for the integration.</inlineHelpText>
    <label>Base Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationService__mdt/IntegrationService__mdt.object-meta.xml
<CustomObject>
    <description>Information about a specific service related to an integration configuration.</description>
    <label>Integration Service</label>
    <pluralLabel>Integration Services</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationService__mdt/fields/IntegrationConfiguration__c.field-meta.xml
<CustomField>
    <fullName>IntegrationConfiguration__c</fullName>
    <label>Integration Configuration</label>
    <referenceTo>IntegrationConfiguration__mdt</referenceTo>
    <relationshipLabel>Integration Services</relationshipLabel>
    <relationshipName>Integration_Services</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/IntegrationService__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <description>The path for the integration service. Used together with the base path for the related integration configuration.</description>
    <inlineHelpText>The path for the integration service.</inlineHelpText>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationController.cls
public class IntegrationController {

  private HttpRequest request;
  private HttpResponse response;
  private String baseEndpoint;
  private String serviceEndpoint;
  private String requestMethod;


  public IntegrationController() {
    this.request = new HttpRequest();
  }

  public void initRequest(String integrationConfigName, String integrationServiceName){
    IntegrationConfiguration__mdt config = getIntegrationConfig(integrationConfigName);
    IntegrationService__mdt service = getIntegrationService(integrationConfigName, integrationServiceName);
    if(config != null){
      setBaseEndpoint(config.BaseEndpoint__c);
    }
    if(service != null){
      setServiceEndpoint(service.Path__c);
    }
  }

  public void sendRequest(){
    response = new Http().send(request);
  }

  private IntegrationConfiguration__mdt getIntegrationConfig(String configName){
    return [SELECT Id, DeveloperName, BaseEndpoint__c FROM IntegrationConfiguration__mdt WHERE DeveloperName = :configName LIMIT 1];
  }

  private IntegrationService__mdt getIntegrationService(String configName, String serviceName){
    return [SELECT Id, DeveloperName, Path__c,IntegrationConfiguration__c FROM IntegrationService__mdt WHERE DeveloperName = :serviceName AND IntegrationConfiguration__c = :configName LIMIT 1];
  }

  public HttpRequest getRequest(){
    return this.request;
  }

  public HttpResponse getResponse(){
    return this.response;
  }

  public String getBaseEndpoint(){
    return this.baseEndpoint;
  }

  public String getServiceEndpoint(){
    return this.serviceEndpoint;
  }

  public String getRequestMethod(){
    return this.requestMethod;
  }

  public void setRequest(HttpRequest request){
    this.request = request;
  }

  public void setBaseEndpoint(String baseEndpoint){
    this.baseEndpoint = baseEndpoint;
  }

  public void setServiceEndpoint(String serviceEndpoint){
    this.serviceEndpoint = serviceEndpoint;
  }

  public void setRequestMethod(String requestMethod){
    this.requestMethod = requestMethod;
  }

  public void setNamedCredential(){
    
  }

}