force-app/main/default/objects/IntegrationService__mdt/IntegrationService__mdt.object-meta.xml
<CustomObject>
    <description>Information about a specific service related to an integration configuration.</description>
    <label>Integration Service</label>
    <pluralLabel>Integration Services</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegrationService__mdt/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>The callout method used with the service.</description>
    <inlineHelpText>The callout method used with the service.</inlineHelpText>
    <label>Http Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IntegrationService__mdt/fields/IntegrationConfiguration__c.field-meta.xml
<CustomField>
    <fullName>IntegrationConfiguration__c</fullName>
    <label>Integration Configuration</label>
    <referenceTo>IntegrationConfiguration__mdt</referenceTo>
    <relationshipLabel>Integration Services</relationshipLabel>
    <relationshipName>Integration_Services</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/IntegrationService__mdt/fields/MockResponse__c.field-meta.xml
<CustomField>
    <fullName>MockResponse__c</fullName>
    <description>The Mock response returned by the service.</description>
    <label>Mock Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IntegrationService__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <description>The path for the integration service. Used together with the base path for the related integration configuration.</description>
    <inlineHelpText>The path for the integration service.</inlineHelpText>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CalloutMock.cls
@isTest
global class CalloutMock implements HttpCalloutMock {
  protected Integer code;
  protected String status;
  protected String bodyAsString;
  protected Blob bodyAsBlob;
  protected Map<String, String> responseHeaders;

  public CalloutMock() {
    this.code = null;
    this.status = null;
    this.bodyAsString = null;
    this.bodyAsBlob = null;
    this.responseHeaders = new Map<String, String>();
  }

  public HTTPResponse respond(HTTPRequest req) {
    HttpResponse resp = new HttpResponse();
    resp.setStatusCode(code);
    resp.setStatus(status);

    if (bodyAsBlob != null) {
      resp.setBodyAsBlob(bodyAsBlob);
    } else {
      resp.setBody(bodyAsString);
    }

    if (responseHeaders == null || responseHeaders.isEmpty()) {
      return resp;
    }
    for (String key : responseHeaders.keySet()) {
      resp.setHeader(key, responseHeaders.get(key));
    }
    return resp;
  }

  public void setMock(Integer code, String status, String serviceName) {
    Map<String, Object> mock = (Map<String, Object>) JSON.deserializeUntyped(getMock(serviceName));
    Map<String, Object> mockResponse = (Map<String, Object>) mock.get(String.valueOf(code));

    this.code = code;
    this.status = status;
    this.bodyAsString = String.valueOf(mockResponse.get('body'));

    Test.setMock(HttpCalloutMock.class, this);
  }

  private String getMock(String serviceName) {
    List<IntegrationService__mdt> service = [
      SELECT Id, DeveloperName, HttpMethod__c, Path__c, IntegrationConfiguration__c, MockResponse__c
      FROM IntegrationService__mdt
      WHERE DeveloperName = :serviceName
      LIMIT 1
    ];
    if (service.isEmpty()) {
      throw new MockNotFoundException();
    }
    return service[0].MockResponse__c;
  }

  public class MockNotFoundException extends Exception {
  }
}